general:
  data_path: null
  pretrained_path: null
  iterations: 50000
  num_workers: 8
  global_batch_size: 128
  global_seed: 0
  gpu_offset: 0
  mixed_precision: True
  image_size: 256
  schedule_name: "linear"
  loss_weight_type: "constant" # "constant", "uw",
  vae: "ema" # "ema" or "mse"
  num_tokens: 256
  topk: 1.0
  type: "add"
  init_type: "zero" # "zero"
  gate_type: "linear" # "PT", "FT"
  pt_depth: 12
  gate_regul: True

optim:
  lr: 1e-4
  weight_decay: 0.0

defaults:
  - data: FFHQ # FFHQ or ImageNet
  - models: DiT
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled
logs:
  log_every: 100
  ckpt_every: 10000 #50_000
  results_dir: results/main/${data.name}/${general.schedule_name}_scheduling/${general.num_tokens}_tokens/${general.type}/${general.init_type}/${general.gate_type}_gate
  project_name: "DMP"

# Disable hydra log files
hydra:
  run:
    dir: .
  output_subdir: null


eval:
  samples_dir: samples/main/${data.name}/${general.schedule_name}_scheduling/${general.num_tokens}_tokens/${general.type}/${general.init_type}/${general.gate_type}_gate
  per_proc_batch_size: 25
  num_fid_samples: 50000
  cfg_scale: 1.5
  num_sampling_steps: 250
  ckpt_path:
    version: 0
    iterations: ${general.iterations}